### ISSUE TITLE
Improve indexing metadata

### ISSUE THREAD

**Issue by milkysoft** [artipie/gem-adapter#113] opened 2021-08-03 05:48 UTC
Currently when new gem being pushed, all gems should be copied from server to create new metadata and copy it back to server.

Instead of copy all gems, just copy existing requited metadata files to create new metadata, including newly submitted gem

```
file = File.open("specs.4.8")
file_data = file.read
Marshal.load(file_data)


=> [["builder", #<Gem::Version "3.2.4">, "ruby"]] 


obj = Marshal.load(file_data)[0]
=> ["builder", #<Gem::Version "3.2.4">, "ruby"]

obj[1].version
=> "3.2.4" 



Marshal.load(File.open("latest_specs.4.8").read)
 => [["builder", #<Gem::Version "3.2.4">, "ruby"]] 


Marshal.load(File.open("prerelease_specs.4.8").read)
 => []

**Comment by g4s8** [comment] 2021-08-04 07:57
@milkysoft duplicate of #110 ?

**Closed** 2021-08-05 05:54 UTC
Labels: duplicate
